🔀 Kakao oauth 적용
themoment-team/hello-gsm-back pull request #17
Opened 2022-05-17 03:15 UTC by chanwoo00106

## 개요 💡

> 이메일 인증을 버리고 kakao 로그인으로 변경하였습니다

## 작업 내용 ⌨️

- `/auth/kakao` 에 카카오 로그인 적용
- `/auth/kakao/callback`에서 유저 정보를 받고 쿠키와 함께 redirect
   - 첫 로그인이면 `registerToken`과 함께 회원 가입 페이이지로
   - 두 번 이상이면 `accessToken`, `refreshToken`과 함께 메인 페이지로
- `/auth/register`에서는 user 정보를 받아서 db에 저장

## `/auth/register` 를 만든 이유 ✨

> kakao에서 입학 원서 작성에 필요한 회원 정보를 필 수로 받아 올 수 없어서 따로 입력하게 하였습니다.

## 검토 해야 할 부분 🚨

> register 부분이 살짝 불안 해서 한 번 검토해 주세요
> 참고로 user 존재 여부는 passport에서 처리해 줬습니다.

2022-05-17 03:17 UTC, NohGaSeong approved these changes

2022-05-17 05:01 UTC, jyeonjyan requested changes
빠르게 만드느라 그런 것 같은데 변수명이나 클래스 네이밍이 보다 명확했으면 좋겠어요.
리뷰에 답변 부탁합니다 수고했어요 👻

2022-05-17 05:01 UTC, jyeonjyan commented on src/auth/auth.controller.ts
> +    }
1. 나중에 클린코드라는 책을 읽어보면 알겠지만, 가독성이 높은 코드를 작성하기 위해 `if ~ else` 문을 피하는 방법이 있어요.
> https://code-anthropoid.tistory.com/89

2. 매개변수 "accessToken", "refreshToken"은 개발자의 휴먼에러를 발생시킬 수 있어요.
> 전역 변수로 관리하거나 Utils 성 변수로 관리해보는게 좋을 것 같아요.

2022-05-17 05:01 UTC, jyeonjyan commented on src/auth/auth.controller.ts
> +  async refresh(@User() data: AtUser, @Res() res: Response) {
1. cookie 관련 로직을 정규화 혹은 리팩토링 할 수 있어 보여요.
궁극적으로 하고자 하는게 kakaoLogin() / `res.cookie` 와 비슷해 보여서 제안드려요  :)

2022-05-17 05:01 UTC, jyeonjyan commented on src/auth/auth.service.ts
> +    } else {
리팩토링이 필요해 보여요

2022-05-17 05:01 UTC, jyeonjyan commented on src/auth/dto/register.dto.ts
> +export class RegisterDto {
보다 더 자세히 명명해야할 것 같아요. 클래스 이름이 관심사를 명확하게 드러내지 못해요.

2022-05-17 05:01 UTC, jyeonjyan commented on src/auth/strategies/at.strategy.ts
> +    });
잘했네요 이렇게 처리하면 로그아웃을 보다 안전하게 처리할 수 있어요 :)

2022-05-17 05:01 UTC, jyeonjyan commented on src/auth/strategies/at.strategy.ts
> +    return { user_idx: user.user_idx, accessToken };
리턴타입이 `boolean, entity` 로 두 가지로 보이는데 ts에서는 가능하다고 하네요.
하지만 validation 함수는 "유효성 검사"에만 관심이 있어야 하니 엔티티를 리턴하는건 분리시키는게 좋아보여요!
@chanwoo00106 생각은 어떤가요 ?

2022-05-17 06:51 UTC, ssyy0122 approved these changes

2022-05-17 06:51 UTC, siwony approved these changes

2022-05-17 10:07 UTC, chanwoo00106 commented on src/auth/auth.controller.ts
> +    }
괜찮은 것 같아요 한 번 바꿔보겠습니다!

2022-05-17 10:11 UTC, chanwoo00106 commented on src/auth/auth.service.ts
> +    } else {
리팩토링을 아직 공부하지 않아서 저걸 어떻게 바꿔야 할지 감이 오질 않아요 ㅠㅠ
힌트라도...

2022-05-17 10:14 UTC, chanwoo00106 commented on src/auth/strategies/at.strategy.ts
> +    });
감사합니다!!

2022-05-17 10:20 UTC, chanwoo00106 commented on src/auth/strategies/at.strategy.ts
> +    return { user_idx: user.user_idx, accessToken };
저 부분은 passport 의 `validate` 분인데 저기서 `false`를 리턴 하면 passport가  unauthorization 에러를 발생 시켜줘서 저렇게 작성했습니다. 반대로 `true`나 `entity`를 리턴 하면 에러 없이 통과하게 되고요

2022-05-17 10:23 UTC, chanwoo00106 commented on src/auth/dto/register.dto.ts
> +export class RegisterDto {
`SignInDto` 로 하면 될까요? 아니면 다른 거??
뭘로 하면 좋을지 떠오르지 가 않네요 ㅠㅠ

2022-05-17 10:41 UTC, chanwoo00106 commented on src/auth/auth.controller.ts
> +  async refresh(@User() data: AtUser, @Res() res: Response) {
오 많이 짧아 질 것 같네요! 감사합니다

2022-05-18 06:23 UTC, jyeonjyan commented on src/auth/strategies/at.strategy.ts
> +    return { user_idx: user.user_idx, accessToken };
> 반대로 true나 entity를 리턴 하면 에러 없이 통과하게 되고요.

**첫번째.**
false 를 리턴하면 에러가 발생한다는 부분은 이해했어요. (감사합니다.)
하지만 이러한 배경의 스펙을 갖고 설계 했다고 해도 함수가 SRP 하지 않아요.
validate 함수는 true/false 를 통해 passport가 unauthorization 에러를 터지게 할건지 아닌지만 담당했으면 좋겠어요.

**두번째.**
검증과 엔티티 리턴 책임을 분리하고 함수 이름을 재정의 하는걸 제안할게요.
나중에 유지보수를 하게 된다면 passport 스펙을 알지 않는 이상 해당 함수명을 보고 역할을 알기 어려울 것 같아요.

**추가적으로..**
나중의 유지보수를 위해 tsdocs 을 작성해 보는게 어떤가요 ?

2022-05-18 06:29 UTC, jyeonjyan commented on src/auth/dto/register.dto.ts
> +export class RegisterDto {
음 .. 명명을 제안한건 가독성과 협업/유지보수를 위함이예요.
길어도 좋아요 저 Dto가 어떤 역할을 하는지 잘 드러내기만 해도 돼요! 
로그인만을 담당한다면. `SignInDto`도 좋겠네요!

2022-05-18 06:37 UTC, jyeonjyan commented on src/auth/auth.service.ts
> +    } else {
공통적으로 처리 가능한 부분(교집합)을 찾아요.
그 교집합에 작업 4개가 있고 예외로 작업 1개가 있다면. if 문에 예외(작은 범위)를 넣고 처리하는게 명확해요.

예를 들어 
a~c의 범위에서 a 혹은 b 로 시작하는 단어에 대해서는 두 단어를 붙여요. (큰 범위)
단어가 c 로 시작하는 단어는 무시해요.  (작은 범위)

교집합 `a||b`를 else 로 잡고, c를 예외로 잡으면 c일때는 무시하고 나머지는 붙인다. 라고 가독성 좋은 코드를 짤 수 있어요.
코드가 아래와 같다면. c일때는 return 되기에 아래 오는 statement는 무시되니 side-effect 도 없을거예요.

```java
for(String s : strList){
  if(s.charAt(0) == 'c'){
     return;
  }
  stringBuilder.append(s)
}
```

2022-05-18 07:06 UTC, chanwoo00106 commented on src/auth/dto/register.dto.ts
> +export class RegisterDto {
아 오타가 났네요 `SignInDto` 가 아니라 `SignUpDto`요 ㅠㅠ

2022-05-18 07:07 UTC, chanwoo00106 commented on src/auth/auth.service.ts
> +    } else {
뭔가 느낌은 알 것 같아요 수정 했는데 한 번 봐주세요

2022-05-18 07:37 UTC, chanwoo00106 commented on src/auth/strategies/at.strategy.ts
> +    return { user_idx: user.user_idx, accessToken };
> validate 함수는 true/false 를 통해 passport가 unauthorization 에러를 터지게 할건지 아닌지만 담당했으면 좋겠어요.

그럼 false 말고 null을 리턴하는 건 어떨까요?
저 부분에서 entity를 return 해야지 모든 요청에서 `req.user`로 entity를 참조할 수 있거든요...

> 검증과 엔티티 리턴 책임을 분리하고 함수 이름을 재정의 하는걸 제안할게요.

상속 받은 거여서 함수 이름을 재정의 하는 건 힘들 것 같아요.

> 나중의 유지보수를 위해 tsdocs 을 작성해 보는게 어떤가요 ?

시간 나면 해보겠습니다 ㅠ

2022-05-18 07:51 UTC, jyeonjyan commented on src/auth/auth.service.ts
> +    } else {
음.. ㅎㅎ `if - if - 공통` 으로 설계하면 될 것 같아.
각 조건마다 return 을 주기 때문에 filter 됨 (위에 조건과 관련 없음)을 보장하잖아.

2022-05-18 07:51 UTC, jyeonjyan commented on src/auth/strategies/at.strategy.ts
> +    return { user_idx: user.user_idx, accessToken };
> 그럼 false 말고 null을 리턴하는 건 어떨까요?

일단 애플리케이션 특히 백엔드에서 null을 직접적으로 다루는건 위험 함. 하지만.. null을 허용할 수 있는 구간이 몇 있음.
1. DB 에 null이 절대로 저장되지 않음을 보장하고 비즈니스 딴에서만 null 갖고 있으면 될 때.
2. ts 내부적으로 null을 다루는 예외(nullPointerException)이 치명적이지 않을 때.
3. 절대 널 아님을 단언할 수 있을 때. 오히려 null 이라면 실행시점에 Exception이라는걸 알려야 할 때.

2022-05-18 08:31 UTC, chanwoo00106 commented on src/auth/strategies/at.strategy.ts
> +    return { user_idx: user.user_idx, accessToken };
현재 상황에서는 2, 3번이 해당되어서 null을 사용할 수 있을 것 같습니다.
엔티티를 리턴하지 않으면 거의 모든 요청에서 쿠키를 읽고 에러처리를 해야하는 번거로움이 생길 수 있기 때문에 꼭 필요하다고 생각합니다.

2022-05-18 08:43 UTC, merged