Feature/ged submission
themoment-team/hello-gsm-back pull request #75
Opened 2022-07-24 06:49 UTC by chanwoo00106

## 개요 💡

> 검정고시 점수 입력 수정 기능 추가

## 작업 내용 ⌨️

> 기존 `GedSubmission` 서비스에서 `isPatch`라는 매개변수를 받아서 수정과 생성을 구분했습니다

## 궁금한 점

> 수정 로직과 생성 로직이 비슷해서 둘 이 합쳐서 만들었는데 좀 복잡해진 느낌이 들어요
이렇게 하는 게 맞을까요?

2022-07-24 07:08 UTC, siwony reviewed
근데 `gedSubmission` API가 생성 혹은 수정을 담당하면 HTTP method는 PATCH가 아닌 PUT를 사용하는게 더 알맞지 않아?
PUT은 자원이 있다면 덮어쓰고 없다면 새로 만들고 PATCH는 리소수의 부분 수정을 의미하니까

2022-07-24 07:08 UTC, siwony commented on apps/client/src/application/application.service.ts
> +      });
`isPatch`일때 실행되는 로직을 private 매서드로 빼서 사용하는게 어떠함? (else일 경우도 마찬가지)
```ts
if (isPatch)
    update()
else
    save()
```
예제를 대충 만들었는데 이런식으로 선언형 프로그래밍적으로 코드 작성하면 뭘 하려는지 바로 이해가 되니까 좋은 것 같아서 리뷰함

2022-07-24 13:44 UTC, jyeonjyan requested changes
읽어보고 모르는거 있거나 질문 있으면 바로 코맨트로 달아주세요.
이번 리뷰는 Request changes (변경 요청)으로 하겠습니다 🙂

2022-07-24 13:44 UTC, jyeonjyan commented on apps/client/src/application/application.controller.ts
> +  }
HttpResponse Status 는 어떻게 처리해 ?
FE, BE api spec이 의사결정 됐니?

2022-07-24 13:44 UTC, jyeonjyan commented on apps/client/src/application/application.service.ts
> +    };
이게 혹시 뭐니,,,?
단지 `GedSubmission` 비즈니스의 관심사는 아닌 것 같고..
비즈니스를 만족하기 위한 서브시스템이라고 생각드는데? 

리뷰하는데. 피쳐들이 최소 단위로 잘 나뉘어진게 아닌 것 같아. (SRP, OCP 위반 가능성)

2022-07-24 13:44 UTC, jyeonjyan commented on apps/client/src/application/application.service.ts
> +      throw new BadRequestException('작성된 원서가 없습니다');
음 이런 부분은 valid method로 따로 빼도 될 것 같아.. `userApplicationIsExistValid` method로 !!
이유는 다음과 같아. 협업하는 개발자 입장에서는. "특정 조건에서는 제출, 수정이 불가하다." 만 알고 지나가면 되는데. 세부 조건까지 해석하게 되니깐 가독성을 떨어뜨리는 것 같아.

아래 강의는 validation을 절차적으로 따로 부분이긴한데 강의자체가 객체지향의 느낌을 알기 좋은거라 보는걸 추천할게.
(나는 3학년때 보았지만, 2학년 때 부터 공부해보면 너가 3학년이 됐을 때 설계적으로 더 성장해 있지 않을까?)
> https://youtu.be/dJ5C4qRqAgA?t=4771

2022-07-24 13:44 UTC, jyeonjyan commented on apps/client/src/application/application.service.ts
> +      });
+ 추가적으로
`if ~ else` 를 줄여보는게 어떨까? 보다 비즈니스에 명확한 `if` 조건을 찾는거지.

2022-07-24 13:44 UTC, jyeonjyan commented on apps/client/src/application/application.service.ts
> +   * 검정고시 전용 성적 재출 및 수정
* 재출 -> 제출

이정도로 뭔가 절차지향적으로 로직을 짤거면 부분부분 `//` 통한 로직 설명이 돼 있는게 좋을 것 같아.
큰 틀에서 비즈니스 로직을 만족시키기 위한 서브시스템을 잘 모르겠어서 리뷰에 어려움이 있다.. ! 🥲

2022-07-25 03:42 UTC, chanwoo00106 commented on apps/client/src/application/application.service.ts
> +    };
저 부분은 검정고시의 경우 값이 3가지 밖에 들어가지 않아서 나머지 not null인 컬럼들을 -1로 할당해 주는 곳이에요
나누는 게 좋겠죠?

2022-07-25 04:40 UTC, chanwoo00106 commented on apps/client/src/application/application.service.ts
> +      });
저건 수정과 생성 기능을 하나로 합쳐서 만들다 보니까 어쩔 수 없이 생긴 if 문인데 어떻게 없앨 수 있을까요?
아니면 수정과 생성 기능을 나누는 게 좋을 까요?

2022-07-25 04:58 UTC, jyeonjyan commented on apps/client/src/application/application.service.ts
> +      });
> 수정과 생성 기능을 하나로 합쳐서 만들다

1. 뭔가 귀찮아서 기능을 합쳤다.
2. 비즈니스 요구사항이 `수정/생성` 따로 개별 api 를 쓸 필요가 없다.

이유 때문인 것 같은데 분리해보면 어떨까?
그렇다면 자연스레 결합된 서브시스템이 적절히 분리 될 것 같아.

2022-07-25 05:00 UTC, jyeonjyan commented on apps/client/src/application/application.service.ts
> +    };
응응 저것도 어떻게 보면 valid 인 것 같아. 아니면 generate 해주는 메소드로 빼도 될 것 같고.

generate 유효성
* 검정고시의 경우 3가지의 필드를 제외한 모든 필드는 임의의 값으로 초기화 되어야 한다.

2022-07-25 05:11 UTC, chanwoo00106 commented on apps/client/src/application/application.service.ts
> +      });
지금 분리해 봤는데 한 번 확인해 주세요!

2022-07-25 05:16 UTC, chanwoo00106 commented
> `gedSubmission` API가 생성 혹은 수정을 담당하면 HTTP method는 PATCH가 아닌 PUT를 사용하는게 더 알맞지 않아?
> PUT은 자원이 있다면 덮어쓰고 없다면 새로 만들고 PATCH는 리소수의 부분 수정을 의미하니까

PUT 메서드가 자원이 있다면 덮어쓰고 없다면 새로 만든다는 의미가 있는지는 처음 알았어요!

2022-07-25 05:16 UTC, jyeonjyan approved these changes
중간중간 주석 추가하고. 이 코멘트까지 수정 후 머지하세요.

지금 한 PR 에 변경 및 덮어쓰기가 많아서 리뷰하기 어려우니..
**이 PR #75 멘션해서 `horfix/**` 브랜치 만들어서 리뷰 요청해주렴!**

2022-07-25 05:16 UTC, jyeonjyan commented on apps/client/src/application/application.service.ts
> +      throw new BadRequestException('잘못된 요청입니다');
이건 exist 라는 관심사에 관련이 없긴 함.
메소드 이름을 포괄적으로 `ex: userApplicationValidation` 으로 바꾸던지 세부적으로 valid를 나누던지 하셈.

2022-07-25 05:16 UTC, jyeonjyan commented on apps/client/src/application/application.service.ts
> +      EducationStatus.검정고시
이 부분(값 비교)에는 개행이 오히려 가독성을 떨어뜨림

2022-07-25 05:20 UTC, chanwoo00106 commented on apps/client/src/application/application.controller.ts
> +  }
> HttpResponse Status 는 어떻게 처리해 ?
status code를 말씀하시는 거면 Nest에서 자동으로 `200` 또는 `201`로 해줍니다
`201`로 코드에 명시해 주는 게 좋겠죠?

> FE, BE api spec이 의사결정 됐니?
api 명세서를 만들고 FE한테 한 번 확인 받았습니다!

2022-07-25 05:24 UTC, chanwoo00106 commented on apps/client/src/application/application.service.ts
> +      EducationStatus.검정고시
이건 코드 formatter인 prettier가 자동으로 해주는 거라 어쩔 수가 없어요 ㅠㅠ

2022-07-25 06:32 UTC, chanwoo00106 commented
> 이 PR #75 멘션해서 horfix/** 브랜치 만들어서 리뷰 요청해주렴!

늦게 봤네요 ㅠㅠ
다음부터는 그렇게 하도록 노력하겠습니다!

2022-07-25 06:42 UTC, merged